# Generated by Django 4.1.7 on 2023-02-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boardapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmodel",
            name="good",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="read",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name="boardmodel",
            name="readtext",
            field=models.TextField(blank=True, default="a", null=True),
        ),
    ]
